pipeline{
    agent any
    stages{
        stage('unit test code'){
            agent {  docker { image 'circleci/node:10.15.3' } }
            steps{
                dir('/tmp'){
                    sh 'ls'
                    sh 'echo hii'
                }
            }   
                
            
        }
    }

}