pipeline{
    agent any 
    stages{
        stage('unit test code'){
            steps{
                sh 'mkdir -p /tmp/hub-buildDir/hub'
                dir('/tmp/hub-buildDir/hub'){
                    agent {  docker { image 'circleci/node:10.15.3' } }
                    sh 'ls'
                    sh 'echo hii'
                }
            }   
                
            
        }
    }

}