//library('runUnitTest')

pipeline{
    agent none
    

    stages{
        stage('V2-unit test'){

            agent { docker  { image 'node:10.15.3' } }
            
            environment {
                    CURRENT_HUB = "V2"
                    COVERAGE_THRESHOLD = 80
                    COVERAGE_MAX_DIFF = 1
            }

            steps{
              sh'printenv'
            }   
                
        }
    }
}
